spring:
  batch:
    job:
      names: ${job.name:NONE}
      enabled : false
    jdbc:
      initialize-schema: ALWAYS
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  jpa:
    show-sql: true